### PR TITLE
Fix needless_borrow error, adjust to the Rust update

### PR DESCRIPTION
**Pull request by vadorovsky**
The newest Rust and clippy were reporting a couple needless_borrow errors.
This change fixes them.

The mistake was using `&` on variables which were already of type
`&[u8]`. So we were in fact passing `&&[u8]` to function calls.

There is also a change in the BPF skeleton (also due to the new Rust
version).

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

### CODE REVIEW

**Review by manuelbuil — APPROVED** [review]
LGTM although I don't understand half of what's going on :/

**Comment by vadorovsky** [comment]
To give you more context, this PR is fixing the following error:

```rust
error: this expression borrows a reference (`&[u8]`) that is immediately dereferenced by the compiler
   --> src/lib.rs:366:9
    |
366 |         &container_b,
    |         ^^^^^^^^^^^^ help: change this to: `container_b`
    |
    = note: `-D clippy::needless-borrow` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&[u8]`) that is immediately dereferenced by the compiler
   --> src/lib.rs:380:31
    |
380 |         .update(&process_key, &process_b, libbpf_rs::MapFlags::empty())?;
    |                               ^^^^^^^^^^ help: change this to: `process_b`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&[u8]`) that is immediately dereferenced by the compiler
   --> src/lib.rs:413:9
    |
413 |         &container_b,
    |         ^^^^^^^^^^^^ help: change this to: `container_b`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: this expression borrows a reference (`&[u8]`) that is immediately dereferenced by the compiler
   --> src/lib.rs:433:31
    |
433 |         .update(&process_key, &process_b, libbpf_rs::MapFlags::empty())?;
    |                               ^^^^^^^^^^ help: change this to: `process_b`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: aborting due to 4 previous errors

error: could not compile `lockc`
```

The thing is I added `&` to `container_b` and `process_b` without necessity to do so. They are both already of `&[u8]` type. I didn't realize that this line:

```rust
let container_b = unsafe { plain::as_bytes(&container) ];
```

gives the `&[u8]` variable which doesn't need to be referenced to be borrowed to some other function.

**Comment by vadorovsky** [comment]
Updated the commit message to be (hopefully) a bit more clear.

Ah, and please don't look at the huge file with thousands of lines of change - it's autogenerated from C sources.

**Review by mjura — COMMENTED** [review]
+1

**Pull request merged**
